import { premiumTemplateIds, premiumTemplates } from "./premium/catalog";
export const templatePreviewVersion = 2;
export const legacyTemplateIds = [
  "minimal-01",
  "minimal-02",
  "minimal-03",
  "minimal-04",
  "minimal-05",
  "luxury-01",
  "luxury-02",
  "luxury-03",
  "luxury-04",
  "luxury-05",
  "coffee-01",
  "coffee-02",
  "coffee-03",
  "coffee-04",
  "coffee-05",
  "fastfood-01",
  "fastfood-02",
  "fastfood-03",
  "fastfood-04",
  "fastfood-05",
  "asian-01",
  "asian-02",
  "asian-03",
  "asian-04",
  "asian-05",
  "uzbek-modern-01",
  "uzbek-modern-02",
  "uzbek-premium-01",
  "uzbek-suzani-01",
  "uzbek-ornament-minimal-01",
] as const;
export const templateIds = [
  ...legacyTemplateIds,
  ...premiumTemplateIds,
] as const;
export type TemplateId = (typeof templateIds)[number];
export type Family =
  "minimal" | "luxury" | "coffee" | "fastfood" | "asian" | "uzbek";
export type TemplateDefinition = {
  id: TemplateId;
  name: string;
  family: Family;
  variant: number;
  background: string;
  foreground: string;
  muted: string;
  line: string;
  primary: string;
  layout: string;
  premium?: true;
  radius?: "none" | "small" | "soft";
};
const legacyTemplates: readonly TemplateDefinition[] = [
  {
    id: "minimal-01",
    name: "Everyday",
    family: "minimal",
    variant: 1,
    background: "#fbfaf6",
    foreground: "#26392e",
    muted: "#666c62",
    line: "#dedfd5",
    primary: "#244b3f",
    layout: "rows",
  },
  {
    id: "minimal-02",
    name: "Index",
    family: "minimal",
    variant: 2,
    background: "#fbfaf6",
    foreground: "#26392e",
    muted: "#666c62",
    line: "#dedfd5",
    primary: "#244b3f",
    layout: "index",
  },
  {
    id: "minimal-03",
    name: "Gallery",
    family: "minimal",
    variant: 3,
    background: "#fbfaf6",
    foreground: "#26392e",
    muted: "#666c62",
    line: "#dedfd5",
    primary: "#244b3f",
    layout: "gallery",
  },
  {
    id: "minimal-04",
    name: "Market",
    family: "minimal",
    variant: 4,
    background: "#fbfaf6",
    foreground: "#26392e",
    muted: "#666c62",
    line: "#dedfd5",
    primary: "#244b3f",
    layout: "market",
  },
  {
    id: "minimal-05",
    name: "Journal",
    family: "minimal",
    variant: 5,
    background: "#fbfaf6",
    foreground: "#26392e",
    muted: "#666c62",
    line: "#dedfd5",
    primary: "#244b3f",
    layout: "journal",
  },
  {
    id: "luxury-01",
    name: "Evening",
    family: "luxury",
    variant: 1,
    background: "#191e1b",
    foreground: "#f2ecdc",
    muted: "#c0c4b9",
    line: "#454c40",
    primary: "#d6b782",
    layout: "photographic",
  },
  {
    id: "luxury-02",
    name: "Tasting",
    family: "luxury",
    variant: 2,
    background: "#191e1b",
    foreground: "#f2ecdc",
    muted: "#c0c4b9",
    line: "#454c40",
    primary: "#d6b782",
    layout: "tasting",
  },
  {
    id: "luxury-03",
    name: "Portrait",
    family: "luxury",
    variant: 3,
    background: "#191e1b",
    foreground: "#f2ecdc",
    muted: "#c0c4b9",
    line: "#454c40",
    primary: "#d6b782",
    layout: "portrait",
  },
  {
    id: "luxury-04",
    name: "Salon",
    family: "luxury",
    variant: 4,
    background: "#191e1b",
    foreground: "#f2ecdc",
    muted: "#c0c4b9",
    line: "#454c40",
    primary: "#d6b782",
    layout: "salon",
  },
  {
    id: "luxury-05",
    name: "Panorama",
    family: "luxury",
    variant: 5,
    background: "#191e1b",
    foreground: "#f2ecdc",
    muted: "#c0c4b9",
    line: "#454c40",
    primary: "#d6b782",
    layout: "panorama",
  },
  {
    id: "coffee-01",
    name: "Counter",
    family: "coffee",
    variant: 1,
    background: "#fcf3e8",
    foreground: "#4d3529",
    muted: "#796355",
    line: "#dcc7b0",
    primary: "#794630",
    layout: "counter",
  },
  {
    id: "coffee-02",
    name: "Bakehouse",
    family: "coffee",
    variant: 2,
    background: "#fcf3e8",
    foreground: "#4d3529",
    muted: "#796355",
    line: "#dcc7b0",
    primary: "#794630",
    layout: "bakehouse",
  },
  {
    id: "coffee-03",
    name: "Roast",
    family: "coffee",
    variant: 3,
    background: "#fcf3e8",
    foreground: "#4d3529",
    muted: "#796355",
    line: "#dcc7b0",
    primary: "#794630",
    layout: "board",
  },
  {
    id: "coffee-04",
    name: "Garden",
    family: "coffee",
    variant: 4,
    background: "#fcf3e8",
    foreground: "#4d3529",
    muted: "#796355",
    line: "#dcc7b0",
    primary: "#794630",
    layout: "garden",
  },
  {
    id: "coffee-05",
    name: "Daily",
    family: "coffee",
    variant: 5,
    background: "#fcf3e8",
    foreground: "#4d3529",
    muted: "#796355",
    line: "#dcc7b0",
    primary: "#794630",
    layout: "daily",
  },
  {
    id: "fastfood-01",
    name: "Express",
    family: "fastfood",
    variant: 1,
    background: "#fff9e9",
    foreground: "#271f18",
    muted: "#756353",
    line: "#d8c7ae",
    primary: "#a92e1f",
    layout: "tiles",
  },
  {
    id: "fastfood-02",
    name: "Stack",
    family: "fastfood",
    variant: 2,
    background: "#fff9e9",
    foreground: "#271f18",
    muted: "#756353",
    line: "#d8c7ae",
    primary: "#a92e1f",
    layout: "stack",
  },
  {
    id: "fastfood-03",
    name: "Street",
    family: "fastfood",
    variant: 3,
    background: "#fff9e9",
    foreground: "#271f18",
    muted: "#756353",
    line: "#d8c7ae",
    primary: "#a92e1f",
    layout: "street",
  },
  {
    id: "fastfood-04",
    name: "Quick Pick",
    family: "fastfood",
    variant: 4,
    background: "#fff9e9",
    foreground: "#271f18",
    muted: "#756353",
    line: "#d8c7ae",
    primary: "#a92e1f",
    layout: "quick",
  },
  {
    id: "fastfood-05",
    name: "Grill",
    family: "fastfood",
    variant: 5,
    background: "#fff9e9",
    foreground: "#271f18",
    muted: "#756353",
    line: "#d8c7ae",
    primary: "#a92e1f",
    layout: "grill",
  },
  {
    id: "asian-01",
    name: "Paper",
    family: "asian",
    variant: 1,
    background: "#f5f3ef",
    foreground: "#262625",
    muted: "#66635d",
    line: "#bfbab0",
    primary: "#8c302d",
    layout: "paper",
  },
  {
    id: "asian-02",
    name: "Chapter",
    family: "asian",
    variant: 2,
    background: "#f5f3ef",
    foreground: "#262625",
    muted: "#66635d",
    line: "#bfbab0",
    primary: "#8c302d",
    layout: "chapter",
  },
  {
    id: "asian-03",
    name: "Bento",
    family: "asian",
    variant: 3,
    background: "#f5f3ef",
    foreground: "#262625",
    muted: "#66635d",
    line: "#bfbab0",
    primary: "#8c302d",
    layout: "bento",
  },
  {
    id: "asian-04",
    name: "Ink",
    family: "asian",
    variant: 4,
    background: "#f5f3ef",
    foreground: "#262625",
    muted: "#66635d",
    line: "#bfbab0",
    primary: "#8c302d",
    layout: "ink",
  },
  {
    id: "asian-05",
    name: "Studio",
    family: "asian",
    variant: 5,
    background: "#f5f3ef",
    foreground: "#262625",
    muted: "#66635d",
    line: "#bfbab0",
    primary: "#8c302d",
    layout: "studio",
  },
  {
    id: "uzbek-modern-01",
    name: "Courtyard",
    family: "uzbek",
    variant: 1,
    background: "#f7f2e8",
    foreground: "#213f4a",
    muted: "#586e71",
    line: "#c8d3cf",
    primary: "#165b70",
    layout: "framed",
  },
  {
    id: "uzbek-modern-02",
    name: "Tile",
    family: "uzbek",
    variant: 2,
    background: "#f7f2e8",
    foreground: "#213f4a",
    muted: "#586e71",
    line: "#c8d3cf",
    primary: "#165b70",
    layout: "tile",
  },
  {
    id: "uzbek-premium-01",
    name: "Evening Table",
    family: "uzbek",
    variant: 3,
    background: "#142d37",
    foreground: "#f3ead8",
    muted: "#b7cbc9",
    line: "#41606b",
    primary: "#d7bd82",
    layout: "premium",
  },
  {
    id: "uzbek-suzani-01",
    name: "Gathering",
    family: "uzbek",
    variant: 4,
    background: "#f7f2e8",
    foreground: "#213f4a",
    muted: "#586e71",
    line: "#c8d3cf",
    primary: "#165b70",
    layout: "suzani",
  },
  {
    id: "uzbek-ornament-minimal-01",
    name: "Fine Line",
    family: "uzbek",
    variant: 5,
    background: "#f7f2e8",
    foreground: "#213f4a",
    muted: "#586e71",
    line: "#c8d3cf",
    primary: "#165b70",
    layout: "fine-line",
  },
];
export const templates: readonly TemplateDefinition[] = [
  ...legacyTemplates,
  ...premiumTemplates,
];
export function templateDefinition(id: TemplateId) {
  return templates.find((t) => t.id === id)!;
}

export function previewVersion(template: TemplateDefinition) {
  return template.premium ? 3 : templatePreviewVersion;
}
